### ISSUE TITLE
Add an example with UVs

### ISSUE THREAD

**Issue by Shaun-Fong** [eliemichel/BMeshUnity#5]
apply a material with texture , it didn't show correctly

**Comment by eliemichel** [comment]
Hi @qtghost, could you show the snippet of code that you've used and an image of the result?

**Comment by Shaun-Fong** [comment]
> Hi @qtghost, could you show the snippet of code that you've used and an image of the result?

oh , just nothing . I'm using the example code .

**Comment by eliemichel** [comment]
Ah ok the example code doesn't setup UVs, in order to remain simple and didactic. But indeed I should add an example that includes UVs at the end to show how to set them up, thanks for suggesting! You can try and do it btw, using [`AddVertexAttribute`](https://github.com/eliemichel/BMeshUnity/blob/master/Library/BMesh.cs#L1022) with name "uv" and then access it using [`v.attributes["uv"]`](https://github.com/eliemichel/BMeshUnity/blob/master/Library/BMesh.cs#L119).

**Comment by Shaun-Fong** [comment]
> Ah ok the example code doesn't setup UVs, in order to remain simple and didactic. But indeed I should add an example that includes UVs at the end to show how to set them up, thanks for suggesting! You can try and do it btw, using [`AddVertexAttribute`](https://github.com/eliemichel/BMeshUnity/blob/master/Library/BMesh.cs#L1022) with name "uv" and then access it using [`v.attributes["uv"]`](https://github.com/eliemichel/BMeshUnity/blob/master/Library/BMesh.cs#L119).

that's cool , I'll try

**Comment by eliemichel** [comment]
6 months later, fixed ^^
